# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mike timofiiv
email: blog@fiiv.io
description: > # this means to ignore newlines until "baseurl:"
  A collection of writings by Mike Timofiiv.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.fiiv.io
twitter_username: mtimofiiv
github_username:  mtimofiiv
timezone: Europe/Amsterdam

# Build settings
markdown: kramdown

kramdown:
  input: GFM

defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      permalink: /:year-:month-:day-:title
